### ISSUE TITLE
VIRUS, infected my System, come inside this project!!! NICE

### ISSUE THREAD

**Issue by SamukaDEV** [lycmtz/os#1]
![image](https://user-images.githubusercontent.com/13206430/75044647-c41da880-54a0-11ea-9e27-1e4f92b8933d.png)

ONE OF THOUSAND ERRORS IN MY SECURITY!!!

**Comment by izaac-gao** [comment]
hello, the folder "tools/TASM" is TURBO assembler which is 16-bit real mode DOS program, I guess this makes your anti-virus uncomfortable. there are still other simlar compilers I used. you could delete those files if you are worried and do not want to rebuild the system.

**Comment by SamukaDEV** [comment]
But i made it, and nothing happens, the anti-virus still crazy, and not work like before...

i've changed it too, to other anti-virus, but still the same

**Comment by izaac-gao** [comment]
normally, the anti-virus will scan the download file, then delete suspected virus files. after that, anti-virus stops. you mean the anti-virus goes crazy, can not stop?
